-- ============================================================
-- Code Quest — currículo
-- ============================================================
-- O currículo COMPLETO (6 módulos / 26 aulas: Piskel, Scratch x2,
-- MagicaVoxel, Roblox, Construct) já está populado no banco de produção
-- e é gerenciado pelo tutor em admin.html (sem precisar de SQL).
--
-- Para (re)popular do zero, insira módulos e aulas neste padrão. O conteúdo
-- de cada aula fica na coluna lessons.body (JSONB) com este formato:
--
-- {
--   "intro": "1 frase animando o aluno",
--   "material": [
--     {"t":"h","x":"Título"},
--     {"t":"p","x":"Parágrafo"},
--     {"t":"tip","x":"Dica"},
--     {"t":"anim","cap":"o que a animação mostra"},
--     {"t":"embed","url":"https://youtube/tiktok/insta ou vazio","cap":"vídeo"},
--     {"t":"img","url":"https://... (opcional)","cap":""}
--   ],
--   "resources": [{"label":"...","url":"https://...","note":"...","kind":"piskel|scratch|link|image"}],
--   "challenge": {"x":"desafio","steps":["passo 1","passo 2"]},
--   "english": {"intro":"...","pairs":[["word","palavra"]]}
-- }
--
-- Exemplo de insert de um módulo com aulas (expande um array JSON):
--
-- with m as (
--   insert into public.modules (title, description, tool, position)
--   values ('Piskel — Pixel Art', 'Crie a arte do seu jogo.', 'piskel', 1)
--   returning id
-- ),
-- data as (select $json$[ {"title":"Aula 1 ...","tool":"piskel","position":1,"reward_coins":20,"body":{...}} ]$json$::jsonb as arr)
-- insert into public.lessons (module_id, title, description, tool, position, reward_coins, body)
-- select m.id, e->>'title', e->>'description', (e->>'tool')::tool_kind,
--        (e->>'position')::int, (e->>'reward_coins')::int, e->'body'
-- from m, data, jsonb_array_elements(data.arr) e;
