-- 0008_curso_fixo_estagios.sql
-- 1) Adiciona estágios (kids/teens/young) aos módulos e classifica os existentes.
-- 2) Ajusta as aulas MagicaVoxel para o modelo de curso fixo: remove o prefixo "Dia N:"
--    dos títulos e troca referências internas a "Dia 4" por "próxima aula"/"aula final".
-- NÃO destrutivo e idempotente (mesma abordagem da 0007: update in-place por ordem de position).

alter table public.modules add column if not exists stage text not null default 'kids';

do $chk$
begin
  if not exists (select 1 from pg_constraint where conname = 'modules_stage_check') then
    alter table public.modules
      add constraint modules_stage_check check (stage in ('kids','teens','young'));
  end if;
end
$chk$;

update public.modules set stage = 'kids'  where tool in ('piskel','scratch','magicvoxel');
update public.modules set stage = 'teens' where tool = 'roblox';
update public.modules set stage = 'young' where tool = 'construct';

do $mig$
declare
  v_mod uuid;
  v_ids uuid[];
  n int;
begin
  select id into v_mod from public.modules where tool = 'magicvoxel' order by position, created_at limit 1;
  if v_mod is null then
    insert into public.modules (title, description, tool, position, is_published)
      values ($modt$Construtores de Mundos 3D$modt$, $modd$Crie o seu bichinho e o mundinho dele — tudo feito de cubos mágicos! (MagicaVoxel)$modd$, 'magicvoxel', 999, true)
      returning id into v_mod;
  else
    update public.modules
       set title = $modt$Construtores de Mundos 3D$modt$, description = $modd$Crie o seu bichinho e o mundinho dele — tudo feito de cubos mágicos! (MagicaVoxel)$modd$
     where id = v_mod;
  end if;

  select array_agg(id order by position, created_at) into v_ids
    from public.lessons where module_id = v_mod;
  n := coalesce(array_length(v_ids, 1), 0);

  -- Dia 1
  if n >= 1 then
    update public.lessons
       set title = $t1$Bem-vindo ao mundo dos cubos!$t1$, description = $d1$Abrir o MagicaVoxel, girar a câmera em 3D, escolher cores e colocar/apagar os primeiros cubos.$d1$, body = $b1${"intro":"Abrir o MagicaVoxel, girar a câmera em 3D, escolher cores e colocar/apagar os primeiros cubos.","material":[{"t":"h","x":"2D x 3D: qual é a diferença?"},{"t":"p","x":"No 2D o desenho é chapado, como no papel. No 3D a gente pode GIRAR em volta e ver por cima, por baixo e por trás. Cada cubinho do nosso 3D tem um nome: voxel!"},{"t":"h","x":"Você já joga com voxels!"},{"t":"p","x":"Muitos jogos e desenhos são feitos de cubos, como o mundo do Minecraft. Hoje você vai ser a pessoa que CONSTRÓI esse tipo de mundo, e não só quem joga."},{"t":"h","x":"Passo a passo"},{"t":"h","x":"Abra o programa"},{"t":"p","x":"Abra o MagicaVoxel. Vai aparecer um modelo pronto na tela. Esse é o nosso 'palco' 3D."},{"t":"tip","x":"Não precisa instalar nada nem fazer login. É só abrir e criar!"},{"t":"h","x":"Gire a câmera"},{"t":"p","x":"Segure o botão esquerdo do mouse e arraste no espaço vazio para GIRAR em volta. Role a rodinha para aproximar (zoom)."},{"t":"tip","x":"Brinque de olhar o modelo por cima, por baixo e por trás."},{"t":"h","x":"Escolha uma cor"},{"t":"p","x":"Do lado da tela fica a Palette (caixa de cores). Clique na cor que você quiser usar."},{"t":"h","x":"Attach: coloque cubos"},{"t":"p","x":"Com o modo Attach ligado, clique no modelo para colar um voxel. Segure e arraste para colocar vários de uma vez!"},{"t":"h","x":"Erase: apague os erros"},{"t":"p","x":"Clique no botão Erase e depois clique nos cubos que quer tirar. Errou? Use o Undo (Ctrl+Z) para voltar."},{"t":"tip","x":"Errar faz parte! Todo construtor apaga e tenta de novo."},{"t":"h","x":"Construa uma torre colorida"},{"t":"p","x":"Empilhe cubos de cores diferentes e faça uma torre ou um docinho. Gire para ver de todos os lados."}],"resources":[{"label":"Baixar o MagicaVoxel","url":"https://ephtracy.github.io/","note":"Gratuito, sem conta","kind":"link"},{"label":"Site oficial — magicavoxel.net","url":"https://www.magicavoxel.net/","note":"","kind":"link"}],"challenge":{"x":"A Torre Arco-Íris. Terminou? Ajude um colega a girar a câmera dele. :)","steps":["Construa uma torre usando pelo menos 4 cores diferentes.","Ela precisa ter uma parte que 'sai para o lado' (não pode ser só reta!).","Gire a câmera e mostre sua torre por 3 lados diferentes."]},"english":{"intro":"Ligue cada palavra em inglês à tradução.","pairs":[["Voxel","Cubo 3D"],["Attach","Encaixar"],["Erase","Apagar"],["Palette","Paleta de cores"],["Model","Modelo 3D"],["Undo","Desfazer"]]}}$b1$::jsonb
     where id = v_ids[1];
  else
    insert into public.lessons (module_id, title, description, tool, position, reward_coins, is_published, body)
      values (v_mod, $t1$Bem-vindo ao mundo dos cubos!$t1$, $d1$Abrir o MagicaVoxel, girar a câmera em 3D, escolher cores e colocar/apagar os primeiros cubos.$d1$, 'magicvoxel', 0, 20, true, $b1${"intro":"Abrir o MagicaVoxel, girar a câmera em 3D, escolher cores e colocar/apagar os primeiros cubos.","material":[{"t":"h","x":"2D x 3D: qual é a diferença?"},{"t":"p","x":"No 2D o desenho é chapado, como no papel. No 3D a gente pode GIRAR em volta e ver por cima, por baixo e por trás. Cada cubinho do nosso 3D tem um nome: voxel!"},{"t":"h","x":"Você já joga com voxels!"},{"t":"p","x":"Muitos jogos e desenhos são feitos de cubos, como o mundo do Minecraft. Hoje você vai ser a pessoa que CONSTRÓI esse tipo de mundo, e não só quem joga."},{"t":"h","x":"Passo a passo"},{"t":"h","x":"Abra o programa"},{"t":"p","x":"Abra o MagicaVoxel. Vai aparecer um modelo pronto na tela. Esse é o nosso 'palco' 3D."},{"t":"tip","x":"Não precisa instalar nada nem fazer login. É só abrir e criar!"},{"t":"h","x":"Gire a câmera"},{"t":"p","x":"Segure o botão esquerdo do mouse e arraste no espaço vazio para GIRAR em volta. Role a rodinha para aproximar (zoom)."},{"t":"tip","x":"Brinque de olhar o modelo por cima, por baixo e por trás."},{"t":"h","x":"Escolha uma cor"},{"t":"p","x":"Do lado da tela fica a Palette (caixa de cores). Clique na cor que você quiser usar."},{"t":"h","x":"Attach: coloque cubos"},{"t":"p","x":"Com o modo Attach ligado, clique no modelo para colar um voxel. Segure e arraste para colocar vários de uma vez!"},{"t":"h","x":"Erase: apague os erros"},{"t":"p","x":"Clique no botão Erase e depois clique nos cubos que quer tirar. Errou? Use o Undo (Ctrl+Z) para voltar."},{"t":"tip","x":"Errar faz parte! Todo construtor apaga e tenta de novo."},{"t":"h","x":"Construa uma torre colorida"},{"t":"p","x":"Empilhe cubos de cores diferentes e faça uma torre ou um docinho. Gire para ver de todos os lados."}],"resources":[{"label":"Baixar o MagicaVoxel","url":"https://ephtracy.github.io/","note":"Gratuito, sem conta","kind":"link"},{"label":"Site oficial — magicavoxel.net","url":"https://www.magicavoxel.net/","note":"","kind":"link"}],"challenge":{"x":"A Torre Arco-Íris. Terminou? Ajude um colega a girar a câmera dele. :)","steps":["Construa uma torre usando pelo menos 4 cores diferentes.","Ela precisa ter uma parte que 'sai para o lado' (não pode ser só reta!).","Gire a câmera e mostre sua torre por 3 lados diferentes."]},"english":{"intro":"Ligue cada palavra em inglês à tradução.","pairs":[["Voxel","Cubo 3D"],["Attach","Encaixar"],["Erase","Apagar"],["Palette","Paleta de cores"],["Model","Modelo 3D"],["Undo","Desfazer"]]}}$b1$::jsonb);
  end if;

  -- Dia 2
  if n >= 2 then
    update public.lessons
       set title = $t2$Meu personagem 3D$t2$, description = $d2$Construir um personagem com cabeça, corpo, braços e pernas usando o espelho (mirror) para ficar simétrico.$d2$, body = $b2${"intro":"Construir um personagem com cabeça, corpo, braços e pernas usando o espelho (mirror) para ficar simétrico.","material":[{"t":"h","x":"Simetria: os dois lados iguais"},{"t":"p","x":"Nosso corpo é simétrico: o lado direito parece o esquerdo. O Mirror (espelho) do programa faz isso sozinho — você constrói um olho e o outro aparece do outro lado, igualzinho!"},{"t":"h","x":"Planeje antes de colar"},{"t":"p","x":"Grandes criadores pensam primeiro. Imagine o seu personagem: é um bicho? um robô? um monstrinho fofo? Decida a forma da cabeça e do corpo antes de empilhar os cubos."},{"t":"h","x":"Passo a passo"},{"t":"h","x":"Faça o corpo"},{"t":"p","x":"Comece por um bloco para o corpo. Use a ferramenta Box para criar vários cubos de uma vez e ganhar tempo."},{"t":"tip","x":"Box = você clica e arrasta para 'puxar' uma caixa inteira."},{"t":"h","x":"Ligue o espelho (Mirror)"},{"t":"p","x":"Ative o Mirror no eixo X. Agora tudo que você fizer de um lado aparece igual do outro lado."},{"t":"h","x":"Cabeça e pescoço"},{"t":"p","x":"Coloque a cabeça em cima do corpo. Deixe um pescocinho de 1 cubo, se quiser."},{"t":"h","x":"Braços e pernas"},{"t":"p","x":"Com o espelho ligado, construa 1 braço e 1 perna — o outro lado aparece sozinho, simétrico!"},{"t":"h","x":"Rosto e cores"},{"t":"p","x":"Escolha cores novas na Palette e faça olhos e boca. Pinte a roupa e a pele do seu jeito."}],"resources":[{"label":"Baixar o MagicaVoxel","url":"https://ephtracy.github.io/","note":"Gratuito, sem conta","kind":"link"},{"label":"Site oficial — magicavoxel.net","url":"https://www.magicavoxel.net/","note":"","kind":"link"}],"challenge":{"x":"Dê um superpoder a ele! Guarde bem o nome: ele vai na sua apresentação final.","steps":["Adicione UM detalhe especial: chapéu, antena, asa, rabo ou coroa.","Use o espelho para deixar esse detalhe simétrico (quando fizer sentido).","Dê um nome ao seu personagem — vamos usar na aula de apresentação!"]},"english":{"intro":"Ligue cada palavra em inglês à tradução.","pairs":[["Character","Personagem"],["Mirror","Espelho"],["Box","Caixa"],["Head","Cabeça"],["Body","Corpo"],["Eyes","Olhos"]]}}$b2$::jsonb
     where id = v_ids[2];
  else
    insert into public.lessons (module_id, title, description, tool, position, reward_coins, is_published, body)
      values (v_mod, $t2$Meu personagem 3D$t2$, $d2$Construir um personagem com cabeça, corpo, braços e pernas usando o espelho (mirror) para ficar simétrico.$d2$, 'magicvoxel', 1, 20, true, $b2${"intro":"Construir um personagem com cabeça, corpo, braços e pernas usando o espelho (mirror) para ficar simétrico.","material":[{"t":"h","x":"Simetria: os dois lados iguais"},{"t":"p","x":"Nosso corpo é simétrico: o lado direito parece o esquerdo. O Mirror (espelho) do programa faz isso sozinho — você constrói um olho e o outro aparece do outro lado, igualzinho!"},{"t":"h","x":"Planeje antes de colar"},{"t":"p","x":"Grandes criadores pensam primeiro. Imagine o seu personagem: é um bicho? um robô? um monstrinho fofo? Decida a forma da cabeça e do corpo antes de empilhar os cubos."},{"t":"h","x":"Passo a passo"},{"t":"h","x":"Faça o corpo"},{"t":"p","x":"Comece por um bloco para o corpo. Use a ferramenta Box para criar vários cubos de uma vez e ganhar tempo."},{"t":"tip","x":"Box = você clica e arrasta para 'puxar' uma caixa inteira."},{"t":"h","x":"Ligue o espelho (Mirror)"},{"t":"p","x":"Ative o Mirror no eixo X. Agora tudo que você fizer de um lado aparece igual do outro lado."},{"t":"h","x":"Cabeça e pescoço"},{"t":"p","x":"Coloque a cabeça em cima do corpo. Deixe um pescocinho de 1 cubo, se quiser."},{"t":"h","x":"Braços e pernas"},{"t":"p","x":"Com o espelho ligado, construa 1 braço e 1 perna — o outro lado aparece sozinho, simétrico!"},{"t":"h","x":"Rosto e cores"},{"t":"p","x":"Escolha cores novas na Palette e faça olhos e boca. Pinte a roupa e a pele do seu jeito."}],"resources":[{"label":"Baixar o MagicaVoxel","url":"https://ephtracy.github.io/","note":"Gratuito, sem conta","kind":"link"},{"label":"Site oficial — magicavoxel.net","url":"https://www.magicavoxel.net/","note":"","kind":"link"}],"challenge":{"x":"Dê um superpoder a ele! Guarde bem o nome: ele vai na sua apresentação final.","steps":["Adicione UM detalhe especial: chapéu, antena, asa, rabo ou coroa.","Use o espelho para deixar esse detalhe simétrico (quando fizer sentido).","Dê um nome ao seu personagem — vamos usar na aula de apresentação!"]},"english":{"intro":"Ligue cada palavra em inglês à tradução.","pairs":[["Character","Personagem"],["Mirror","Espelho"],["Box","Caixa"],["Head","Cabeça"],["Body","Corpo"],["Eyes","Olhos"]]}}$b2$::jsonb);
  end if;

  -- Dia 3
  if n >= 3 then
    update public.lessons
       set title = $t3$O mundinho do meu personagem$t3$, description = $d3$Montar um mini-cenário ao redor do personagem: chão, uma árvore, uma casa ou objetos.$d3$, body = $b3${"intro":"Montar um mini-cenário ao redor do personagem: chão, uma árvore, uma casa ou objetos.","material":[{"t":"h","x":"Todo jogo tem um mapa"},{"t":"p","x":"O lugar onde o personagem vive se chama cenário (scene). Nos jogos, é o mapa ou a fase. Um bom cenário conta uma história: floresta, espaço, cidade, fundo do mar..."},{"t":"h","x":"Escala: grande e pequeno"},{"t":"p","x":"Uma árvore deve ser MAIOR que o personagem; uma flor, menor. Cuidar do tamanho (escala) faz o mundo parecer de verdade."},{"t":"h","x":"Passo a passo"},{"t":"h","x":"Crie o chão (ground)"},{"t":"p","x":"Faça uma base plana embaixo do personagem usando a ferramenta Box. Esse é o chão do mundo."},{"t":"tip","x":"Chão verde vira grama; marrom vira terra; azul vira água."},{"t":"h","x":"Plante uma árvore"},{"t":"p","x":"Faça um tronco (marrom) e uma copa (verde) por cima. Lembre: a árvore é maior que o personagem."},{"t":"h","x":"Construa uma casa ou objeto"},{"t":"p","x":"Monte uma casinha simples (paredes + telhado) OU objetos do seu tema: foguete, castelo, cogumelo gigante..."},{"t":"h","x":"Espalhe detalhes"},{"t":"p","x":"Adicione 3 detalhes pequenos: flores, pedras, nuvens ou um caminho de cubos."},{"t":"h","x":"Salve e exporte"},{"t":"p","x":"Salve o arquivo .vox na pasta MEUS MUNDOS. Esse arquivo guarda TUDO para a próxima aula."},{"t":"tip","x":"Salvar sempre! Assim nada se perde de uma aula para a outra."}],"resources":[{"label":"Baixar o MagicaVoxel","url":"https://ephtracy.github.io/","note":"Gratuito, sem conta","kind":"link"},{"label":"Site oficial — magicavoxel.net","url":"https://www.magicavoxel.net/","note":"","kind":"link"}],"challenge":{"x":"Conte uma história. Na próxima aula vamos deixar tudo lindo com luz e sombra!","steps":["O seu cenário precisa deixar claro ONDE o personagem vive.","Inclua pelo menos 3 tipos de objeto diferentes.","Esconda um 'segredo' no mapa (um item escondido atrás de algo)."]},"english":{"intro":"Ligue cada palavra em inglês à tradução.","pairs":[["Scene","Cenário"],["Ground","Chão"],["Tree","Árvore"],["House","Casa"],["World","Mundo"],["Save","Salvar"]]}}$b3$::jsonb
     where id = v_ids[3];
  else
    insert into public.lessons (module_id, title, description, tool, position, reward_coins, is_published, body)
      values (v_mod, $t3$O mundinho do meu personagem$t3$, $d3$Montar um mini-cenário ao redor do personagem: chão, uma árvore, uma casa ou objetos.$d3$, 'magicvoxel', 2, 20, true, $b3${"intro":"Montar um mini-cenário ao redor do personagem: chão, uma árvore, uma casa ou objetos.","material":[{"t":"h","x":"Todo jogo tem um mapa"},{"t":"p","x":"O lugar onde o personagem vive se chama cenário (scene). Nos jogos, é o mapa ou a fase. Um bom cenário conta uma história: floresta, espaço, cidade, fundo do mar..."},{"t":"h","x":"Escala: grande e pequeno"},{"t":"p","x":"Uma árvore deve ser MAIOR que o personagem; uma flor, menor. Cuidar do tamanho (escala) faz o mundo parecer de verdade."},{"t":"h","x":"Passo a passo"},{"t":"h","x":"Crie o chão (ground)"},{"t":"p","x":"Faça uma base plana embaixo do personagem usando a ferramenta Box. Esse é o chão do mundo."},{"t":"tip","x":"Chão verde vira grama; marrom vira terra; azul vira água."},{"t":"h","x":"Plante uma árvore"},{"t":"p","x":"Faça um tronco (marrom) e uma copa (verde) por cima. Lembre: a árvore é maior que o personagem."},{"t":"h","x":"Construa uma casa ou objeto"},{"t":"p","x":"Monte uma casinha simples (paredes + telhado) OU objetos do seu tema: foguete, castelo, cogumelo gigante..."},{"t":"h","x":"Espalhe detalhes"},{"t":"p","x":"Adicione 3 detalhes pequenos: flores, pedras, nuvens ou um caminho de cubos."},{"t":"h","x":"Salve e exporte"},{"t":"p","x":"Salve o arquivo .vox na pasta MEUS MUNDOS. Esse arquivo guarda TUDO para a próxima aula."},{"t":"tip","x":"Salvar sempre! Assim nada se perde de uma aula para a outra."}],"resources":[{"label":"Baixar o MagicaVoxel","url":"https://ephtracy.github.io/","note":"Gratuito, sem conta","kind":"link"},{"label":"Site oficial — magicavoxel.net","url":"https://www.magicavoxel.net/","note":"","kind":"link"}],"challenge":{"x":"Conte uma história. Na próxima aula vamos deixar tudo lindo com luz e sombra!","steps":["O seu cenário precisa deixar claro ONDE o personagem vive.","Inclua pelo menos 3 tipos de objeto diferentes.","Esconda um 'segredo' no mapa (um item escondido atrás de algo)."]},"english":{"intro":"Ligue cada palavra em inglês à tradução.","pairs":[["Scene","Cenário"],["Ground","Chão"],["Tree","Árvore"],["House","Casa"],["World","Mundo"],["Save","Salvar"]]}}$b3$::jsonb);
  end if;

  -- Dia 4
  if n >= 4 then
    update public.lessons
       set title = $t4$Luz, câmera, render!$t4$, description = $d4$Ajustes finais, ligar o modo Render com luz e sombra, exportar a imagem e apresentar para a turma.$d4$, body = $b4${"intro":"Ajustes finais, ligar o modo Render com luz e sombra, exportar a imagem e apresentar para a turma.","material":[{"t":"h","x":"O que é 'render'?"},{"t":"p","x":"Render é quando o computador calcula a LUZ e a SOMBRA e transforma os seus cubos numa imagem de verdade, bonita e brilhante. É como tirar uma foto profissional do seu mundo!"},{"t":"h","x":"Apresentar dá um friozinho — e tudo bem"},{"t":"p","x":"Respire fundo e lembre das suas 3 frases: (1) o nome do personagem, (2) o que ele faz e (3) a parte mais difícil de construir. Você criou isso — pode se orgulhar!"},{"t":"h","x":"Passo a passo"},{"t":"h","x":"Retoques finais"},{"t":"p","x":"Abra o seu arquivo salvo. Conserte o que faltou: uma cor, um detalhe, deixar tudo no lugar."},{"t":"h","x":"Ligue o modo Render"},{"t":"p","x":"No topo, troque para o modo Render. O seu mundo vai ganhar luz e sombra automaticamente. Uau!"},{"t":"tip","x":"Gire a câmera para achar o ângulo mais bonito do seu personagem."},{"t":"h","x":"Ajuste a luz"},{"t":"p","x":"Mexa na luz (sol) e no fundo até o seu personagem ficar bem iluminado e com uma sombra legal."},{"t":"h","x":"Exporte a imagem"},{"t":"p","x":"Salve a imagem (Export / PNG) na pasta MEUS MUNDOS. Essa é a sua obra final!"},{"t":"h","x":"Apresente"},{"t":"p","x":"Mostre a sua imagem na TV e diga as suas 3 frases. Sorria: você é um Construtor de Mundos 3D!"}],"resources":[{"label":"Baixar o MagicaVoxel","url":"https://ephtracy.github.io/","note":"Gratuito, sem conta","kind":"link"},{"label":"Site oficial — magicavoxel.net","url":"https://www.magicavoxel.net/","note":"","kind":"link"}],"challenge":{"x":"A foto perfeita. Pronto! Hora de apresentar e comemorar!","steps":["Ache um ângulo de câmera onde dê para ver o personagem E o cenário.","Deixe a luz batendo de um lado para criar sombra.","Exporte a imagem e escolha um título para a sua obra."]},"english":{"intro":"Ligue cada palavra em inglês à tradução.","pairs":[["Render","Gerar imagem"],["Light","Luz"],["Shadow","Sombra"],["Camera","Câmera"],["Export","Exportar"],["Present","Apresentar"]]}}$b4$::jsonb
     where id = v_ids[4];
  else
    insert into public.lessons (module_id, title, description, tool, position, reward_coins, is_published, body)
      values (v_mod, $t4$Luz, câmera, render!$t4$, $d4$Ajustes finais, ligar o modo Render com luz e sombra, exportar a imagem e apresentar para a turma.$d4$, 'magicvoxel', 3, 20, true, $b4${"intro":"Ajustes finais, ligar o modo Render com luz e sombra, exportar a imagem e apresentar para a turma.","material":[{"t":"h","x":"O que é 'render'?"},{"t":"p","x":"Render é quando o computador calcula a LUZ e a SOMBRA e transforma os seus cubos numa imagem de verdade, bonita e brilhante. É como tirar uma foto profissional do seu mundo!"},{"t":"h","x":"Apresentar dá um friozinho — e tudo bem"},{"t":"p","x":"Respire fundo e lembre das suas 3 frases: (1) o nome do personagem, (2) o que ele faz e (3) a parte mais difícil de construir. Você criou isso — pode se orgulhar!"},{"t":"h","x":"Passo a passo"},{"t":"h","x":"Retoques finais"},{"t":"p","x":"Abra o seu arquivo salvo. Conserte o que faltou: uma cor, um detalhe, deixar tudo no lugar."},{"t":"h","x":"Ligue o modo Render"},{"t":"p","x":"No topo, troque para o modo Render. O seu mundo vai ganhar luz e sombra automaticamente. Uau!"},{"t":"tip","x":"Gire a câmera para achar o ângulo mais bonito do seu personagem."},{"t":"h","x":"Ajuste a luz"},{"t":"p","x":"Mexa na luz (sol) e no fundo até o seu personagem ficar bem iluminado e com uma sombra legal."},{"t":"h","x":"Exporte a imagem"},{"t":"p","x":"Salve a imagem (Export / PNG) na pasta MEUS MUNDOS. Essa é a sua obra final!"},{"t":"h","x":"Apresente"},{"t":"p","x":"Mostre a sua imagem na TV e diga as suas 3 frases. Sorria: você é um Construtor de Mundos 3D!"}],"resources":[{"label":"Baixar o MagicaVoxel","url":"https://ephtracy.github.io/","note":"Gratuito, sem conta","kind":"link"},{"label":"Site oficial — magicavoxel.net","url":"https://www.magicavoxel.net/","note":"","kind":"link"}],"challenge":{"x":"A foto perfeita. Pronto! Hora de apresentar e comemorar!","steps":["Ache um ângulo de câmera onde dê para ver o personagem E o cenário.","Deixe a luz batendo de um lado para criar sombra.","Exporte a imagem e escolha um título para a sua obra."]},"english":{"intro":"Ligue cada palavra em inglês à tradução.","pairs":[["Render","Gerar imagem"],["Light","Luz"],["Shadow","Sombra"],["Camera","Câmera"],["Export","Exportar"],["Present","Apresentar"]]}}$b4$::jsonb);
  end if;

  raise notice 'MagicaVoxel reformulado: modulo=%, aulas_existentes=%', v_mod, n;
end
$mig$;
